version: '3'

services:
  stock_price_predictor:
    image: stock_price_predictor:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888" # jupyter
      - "8050:8050" # dash
    volumes:
      - /home/lethwombie/git/stock_price_predictor/helpers:/helpers
      - /home/lethwombie/git/stock_price_predictor/data:/data
      - /home/lethwombie/git/stock_price_predictor/notebooks:/notebooks
      - /home/lethwombie/git/stock_price_predictor/dash_app:/dash_app
    entrypoint: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--notebook-dir=/notebooks", "--allow-root", "--no-browser", "--NotebookApp.token=''"]
