# python base image
FROM python:3.8-slim-buster
USER root

# update runtime packages
RUN \ 
    apt-get update && \ 
    apt-get install -y

# copy requirements.txt into the container
COPY requirements_dash.txt requirements_dash.txt

# upgrade pip and setuptools
RUN \
    pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r requirements_dash.txt && \
    rm requirements_dash.txt

# ports and volumes
EXPOSE 8050
VOLUME dash_app
