version: '3.6'

  stock_predictor_dashboard:
    image: stock_predictor_dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Australia/Brisbane"      
    ports:
      - "8050:8050" # dash
    volumes:
      - /home/lethwombie/git/stock_price_predictor/dash_app:/dash_app
      - /home/lethwombie/git/stock_price_predictor/helpers:/helpers
    working_dir: /dash_app
    # entrypoint: ["./app_start.sh"]
    entrypoint: ["python", "app.py"]
          