version: '3.6'
services:
  share_price_predictor:
    image: share_price_predictor:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Australia/Brisbane"
    ports:
      - "8050:8050" # dash
    working_dir: /dash_app
    entrypoint: ["./app_start.sh"]
    